### ISSUE TITLE
Songs not found return 500 instead of 404

### ISSUE THREAD

**Issue by cauebs** [BharatKalluri/lyricfetcher#3]
The 404 received in the code remains untreated and the framework passes along a 500, instead of the expected 404.
e.g.: https://pylyricfetcher.herokuapp.com/api/lyricswikia/beatles/tomorrow

**Comment by BharatKalluri** [comment]
Thanks for pointing that out!

I have changed the api such that if the song is not found it returns the error code as 404 in lyrics field of json (It seems like a good idea to me as people get the lyrics from the json)

Closing this issue,Please let me know if you have a better approach.

**Comment by cauebs** [comment]
Well, ideally the server should respond with a 404 status code.
I personally think it's not very elegant to have the status code be sent in the `lyrics` field. If it would be too much of a hassle to change how the server responds right now, you could consider having an aditional field in the json response for the status code, as I've seen in other APIs, such as the Google Maps APIs.
```
>>> r = requests.get(url)
>>> r.status_code
200
>>> r.text
'{"source":"lyricswikia","artist":"beatles","Song":"tomorrow","Lyrics":404}'
```
Ideally, it should look like this:
```
>>> r.status_code
404
>>> r.text
'{"source":"lyricswikia","artist":"beatles","Song":"tomorrow","Lyrics":'', status_code: 404}'
```

But I'm just being a perfeccionist. You've done a terrific job so far, I really like it ;)

**Comment by BharatKalluri** [comment]
Nice! Will work on it for the next version, Thanks for the suggestion!
