### ISSUE TITLE
ModuleNotFoundError: No module named 'lyricfetcher.sources'

### ISSUE THREAD

**Issue by ultran00b** [BharatKalluri/lyricfetcher#5]
Hello!
I just installed on my macOS 10.12 lyricfetcher using pip3, no errors was. But when I try to import your module, Python show me error "ModuleNotFoundError: No module named 'lyricfetcher.sources'".

How to solve this problem?

Thanks, 
ULTRA N00B.

**Comment by BharatKalluri** [comment]
Hey @ultran00b !

My bad, I pushed the wrong version to pypi by mistake.

Corrected the problem in 0.5, Please reinstall the latest version by using the command 

```bash
pip uninstall lyricfetcher && pip install lyricfetcher
```

Closing this issue, feel free to reopen or comment for further questions.
